### ISSUE TITLE
snippet for static pages

### ISSUE THREAD

**Issue by oim37** [AIC-BV/wn-faq-plugin#1]
Hello,

I use static pages and this plugin no have a snippet to choose what category i want to show on this page. 

I use gallery plugin (https://github.com/Hounddd/wn-lightgallery-plugin) and it have snippet with settings same as it have on CMS pages. 

This is very handy as I want to position the questions and answers in the middle of the content in static pages.
Is there any other way or solution?

**Comment by oim37** [comment]
```
[FAQ]
sort = "category_id asc"
categoryId = 1
isFeatured = 0
isSearch = 1
minSearchResults = 10
isTranslated = 1
==
{% component 'FAQ' %}

```
Or how to specify settings in the code itself after ==
If I create a snippet myself, then I'm interested in the parameter
`categoryId = 1`

**Comment by oim37** [comment]
I add this code in Plugin.php

```
public function registerPageSnippets()
    {
            return [
                        'aic\faq\components\faqs' => 'categoryId',
                    ];
    }

```
Seems to be working...

**Comment by AIC-BV** [comment]
> I add this code in Plugin.php
> 
> ```
> public function registerPageSnippets()
>     {
>             return [
>                         'aic\faq\components\faqs' => 'categoryId',
>                     ];
>     }
> ```
> 
> Seems to be working...

Glad to hear it is working!
I have never used snippets before but if it is working it sounds very good to me 😄

**Comment by oim37** [comment]
Yes, all settings are displayed and working. Thanks for a great module.
